name: CI/CD for meep frontend

on:
  workflow_run:
    workflows: ["build-and-push-web"]
    types: [completed]
    branches: [main]
jobs:


  deploy:
    needs: build


    runs-on: ubuntu-latest 

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/meep-site/meep-infra
            docker compose up -d
