name: CI/CD for meep frontend

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Bun Install
      uses: oven-sh/setup-bun@v2

    - run: bun install

  deploy:

    needs: build

    runs-on: ubuntu-latest 

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/meep-site/meep-web
            git pull 
            bun run build
            cd ..
            cd meep-infra
            docker compose up --build 
